#!/bin/bash

db=$1

all="/msu/data/t3fast2/giorgi"

for d in `ls $all | grep '^AA[0-9]j$'`; do
  AA=`ls $all/$d`
  dir="$all/$d/$AA"
  echo "$dir"

  arr=(`echo $AA | sed -n \
    's/^AA\([0-9]\)j-\(.*\)-\(.*\)tev-eA\(.*\)-ptA\(.*\)-ej\(.*\)-ptj\(.*\)$/\1 \2 \3 \4 \5 \6 \7/p'`\
  )

  cd $dir
  dir=`pwd -P`
  cd -

  for p in `ls $dir`; do
    for f in `ls $dir/$p`; do
      echo "$AA/$p/$f"

sqlite3 $db "insert into bh
  (file,dir,particle,njets,energy,part,jet_pt_cut,jet_eta_cut,other_cuts)
  values
  ('$f','$dir/$p','AA','${arr[0]}','${arr[2]}','$p','${arr[6]}','${arr[5]}','ptA${arr[4]} etaA${arr[3]}')
;"

    done
  done
done
