#!/bin/bash

base="$1"
arr=(`echo $base | sed '
  s/^\(.*\)\([0-9]\)j_\([0-9]*\)TeV_\(.*\)_\(.*\)_\(.*\)\(_.*\|$\)/\1 \2 \3 \4 \5 \6/
'`)

echo $base

args="-o $dir/hist/$base.root -j ${arr[1]} -c ${arr[5]} --cache=400"

if [ "$VBF" ]; then
  args="$args --VBF=$VBF"
fi

if [ "${arr[0]}" == "AA" ]; then
  args="$args --AA"
fi

args="$args `sqlite3 $db "
  SELECT bh.dir, bh.file, wt.dir, wt.file
  FROM bh
  JOIN wt ON bh.id = wt.bh_id
  WHERE particle='${arr[0]}' and njets=${arr[1]} and
        energy=${arr[2]} and part='${arr[3]}' and wt.scales='${arr[4]}'
" | sed 's/\(.*\)|\(.*\)|\(.*\)|\(.*\)/--bh=\1\/\2 --wt=\3\/\4/'`"

/home/ivanp/work/bh_analysis/bin/hist_Hjets $args

