#!/bin/bash

db=$1

if [ ! -f $db ]; then
  sqlite3 $db "create table bh (
    id INTEGER PRIMARY KEY,
    file TEXT,
    dir TEXT,
    particle TEXT,
    njets INTEGER,
    process TEXT,
    energy REAL,
    part TEXT,
    scales TEXT,
    pdf TEXT,
    jet_pt_cut REAL,
    jet_eta_cut REAL,
    other_cuts TEXT,
    comment TEXT
  );"
  sqlite3 $db "create table wt (
    id INTEGER PRIMARY KEY,
    file TEXT,
    dir TEXT,
    bh_id INTEGER,
    bh_file TEXT,
    bh_dir TEXT,
    scales TEXT,
    pdf TEXT,
    jet_alg TEXT,
    comment TEXT
  );"
  sqlite3 $db ".dump"
fi
